server:
  port: 8020
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: customser_feign
    api-b:
      path: /api-b/**
      serviceId: customser_ribbon